[package]
name = "hello-world"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.6", features = ["openssl"] }
env_logger = "0.8"
futures = "0.3"
log = "0.4"

[dev-dependencies]
actix-rt = "1"
